Save last used settings in sample app
sonect/sonect-shop-sdk-android pull request #7
Opened 2020-11-11 13:49 UTC by dryaz

2020-11-11 14:04 UTC, andre-sonect approved these changes

2020-11-12 07:18 UTC, igor-giziy requested changes

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/MainActivityViewModel.kt
> +class MainActivityViewModel(private val app: Application) : AndroidViewModel(app) {
AndroidViewModel -> ViewModel

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/MainActivityViewModel.kt
> +    private val configRepository: ConfigRepository = ConfigRepository(app.getSharedPreferences("SampleApp", Context.MODE_PRIVATE))
Move ConfigRepository to constructor

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/MainActivityViewModel.kt
> +    val state: LiveData<DataState>
add blank line top

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/SdkWrapperActivityViewModel.kt
> +    val state: LiveData<DataState>
add blank line top

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/SdkWrapperActivityViewModel.kt
> +class SdkWrapperActivityViewModel(private val app: Application) : AndroidViewModel(app) {
AndroidViewModel -> ViewModel

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/SdkWrapperActivityViewModel.kt
> +    private val configRepository: ConfigRepository = ConfigRepository(app.getSharedPreferences("SampleApp", Context.MODE_PRIVATE))
Move ConfigRepository to constructor

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/SdkWrapperActivityViewModel.kt
> +    private fun getClientId(): String? = (configRepository.get().find { it is Config.ClientId } as? Config.ClientId)?.value
move functions block after `init` (constructor)

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/SdkWrapperActivityViewModel.kt
> +    private fun calculateSignature(): String {
View model isn't the right place for signature calculation

2020-11-12 07:18 UTC, igor-giziy commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/ConfigSetBuilder.kt
> +class ConfigSetBuilder {
In that case with kotlin we don't need builder pattern

2020-11-12 08:10 UTC, dryaz commented on sample/src/main/java/ch/sonect/sdk/shop/integrationapp/MainActivityViewModel.kt
> +class MainActivityViewModel(private val app: Application) : AndroidViewModel(app) {
Need context in here for prefs

2020-11-12 11:17 UTC, merged